name: test

on:
  pull_request:
    paths-ignore:
      - 'doc/**'
  push:
    branches:
      - main

jobs:
  tests:
    name: Run unittests Python ${{ matrix.python-version }}
    runs-on:
      - ubuntu-latest
      - windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.7"
          - "3.11"
    steps:
      - uses: actions/checkout@v4
      - name: Install Poetry
        run: pipx install poetry
      - name: Install Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'
      - run: poetry install
      - run: poetry run pytest ./tests
